export const hints = {
	mobile: "mobile view",
	tab: "tablets view",
	action: "use this to create draw new shapes",
	save: "click this to save or create canvas",
	cssType: "elem comes with this styling",
	elemType: "create an elem with this tag",
	undo: "click to undo",
	redo: "click to redo",
	exportFormat: " click to select export type",
	importInfo: "click to import a custom style",
	uploadInfo: "all your images is kept here",
	helpInfo: "Shortcuts,Tips and How-Tos",
	openUpdateModal: "click to open update modal for this elem",
	moveUp:
		"click to move the active elem upwards depending on the style of the parent",
	moveDown:
		"click to move the active elem downwards depending on the style of the parent ",
	duplicateHint: "click to duplicate the active elem shortcut-press 'd' ",
	createHint: 'click to enter create mode, shortcut-press "c"',
	importHint: 'click to imports, shortcut-press "i"',
	presetHint: 'click to enter presets mode,shortcut-press "p" ',
	resizeHint: 'click to enter resize mode,shortcut-press "r" ',
	aiHint: "click to ask ai coming soon in V2",
	exportHint: "this runs an export on the ACTIVE/SELECTED BLOCK/Elem",
	changeImageHint: "click to change this image",
};
